name=c_gfx
version=0.1.0
author=Nirison
maintainer=Nirison
sentence=Minimal immediate-mode embedded graphics library.
paragraph=Lightweight C graphics library using immediate pixel drawing API.
category=Display
architectures=*
